AWSTemplateFormatVersion: 2010-09-09
Description: Deploys an S3 Bucket
Parameters:
  Bucketname:
    Type: String
    Description: Enter the S3 bucket name.
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Bucketname
      Tags:
        - Key: automation
          Value: Cloudformation
        - Key: cost-code
          Value: DTS
Outputs: 
  S3BucketName:
    Value: !Ref 'S3Bucket'
    Description: The name of the S3 bucket